// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

package sxx_micro_book_srv_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type Request struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Request) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Request) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*Error)(nil), "sxx.micro.book.srv.auth.Error")
	proto.RegisterType((*Request)(nil), "sxx.micro.book.srv.auth.Request")
	proto.RegisterType((*Response)(nil), "sxx.micro.book.srv.auth.Response")
}

func init() { proto.RegisterFile("proto/auth/auth.proto", fileDescriptor_82b5829f48cfb8e5) }

var fileDescriptor_82b5829f48cfb8e5 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xbf, 0x4e, 0xf3, 0x40,
	0x10, 0xc4, 0x3f, 0x7f, 0xc4, 0xb1, 0x59, 0x0a, 0xa4, 0x15, 0x7f, 0xac, 0x14, 0xc8, 0xb8, 0x4a,
	0x75, 0x48, 0x09, 0x2f, 0x80, 0x04, 0x05, 0x05, 0x14, 0x17, 0x90, 0x90, 0xa8, 0x9c, 0xf3, 0x4a,
	0x58, 0x4e, 0x72, 0xe6, 0xf6, 0x1c, 0xe5, 0xf1, 0x78, 0x34, 0x74, 0x6b, 0x43, 0x45, 0xa8, 0x68,
	0xac, 0xfd, 0x69, 0x66, 0x67, 0x3d, 0x3a, 0x38, 0x6d, 0x9d, 0xf5, 0xf6, 0xaa, 0xec, 0xfc, 0x9b,
	0x7c, 0x94, 0x30, 0x9e, 0xf3, 0x6e, 0xa7, 0xd6, 0xb5, 0x71, 0x56, 0x2d, 0xad, 0x6d, 0x14, 0xbb,
	0xad, 0x0a, 0x72, 0x31, 0x87, 0xf8, 0xce, 0x39, 0xeb, 0x10, 0x61, 0x64, 0x6c, 0x45, 0x59, 0x94,
	0x47, 0xd3, 0x58, 0xcb, 0x8c, 0x67, 0x30, 0xae, 0xc8, 0x97, 0xf5, 0x2a, 0xfb, 0x9f, 0x47, 0xd3,
	0x43, 0x3d, 0x50, 0xb1, 0x80, 0x44, 0xd3, 0x7b, 0x47, 0xec, 0x83, 0xa5, 0x63, 0x72, 0xf7, 0x95,
	0x2c, 0x8e, 0xf4, 0x40, 0x38, 0x81, 0x34, 0x4c, 0x8f, 0xe5, 0x9a, 0x86, 0xe5, 0x6f, 0xc6, 0x13,
	0x88, 0xbd, 0x6d, 0x68, 0x93, 0x1d, 0x88, 0xd0, 0x43, 0xd1, 0x42, 0xaa, 0x89, 0x5b, 0xbb, 0x61,
	0xc2, 0x0c, 0x12, 0xee, 0x8c, 0x21, 0x66, 0x89, 0x4d, 0xf5, 0x17, 0xe2, 0x35, 0xc4, 0x14, 0xfe,
	0x57, 0x42, 0x8f, 0x66, 0x17, 0x6a, 0x4f, 0x31, 0x25, 0xad, 0x74, 0x6f, 0xfe, 0xf9, 0xe2, 0xec,
	0x23, 0x82, 0x64, 0x41, 0x6e, 0x5b, 0x1b, 0xc2, 0x17, 0x38, 0x7e, 0x28, 0x1b, 0xba, 0x91, 0x2b,
	0x4f, 0x41, 0xc6, 0x7c, 0x6f, 0xf6, 0x50, 0x7e, 0x72, 0xf9, 0x8b, 0xa3, 0x6f, 0x52, 0xfc, 0xc3,
	0x57, 0xc0, 0x5b, 0x5a, 0x3d, 0x33, 0xb9, 0xbf, 0x0f, 0x5f, 0x8e, 0xe5, 0x79, 0xe7, 0x9f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x86, 0x39, 0x9e, 0x2b, 0xf7, 0x01, 0x00, 0x00,
}
